### ISSUE TITLE
Launch additional services in separate container

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab-launch#119]
The additional services (like Postgres or RabbitMQ) should be started as additional Docker services. This could for example be achieved via docker-compose.

AiiDAlab-launch would likely need some major revision to then support this, since it currently uses docker directly to manage the container(s).

## Sub-tasks:

- [x] Create proof-of-concept docker-compose file that demonstrates the approach
- [ ] Evaluate how we want to manage multiple containers within the context of aiidalab-launch (docker-compose, manually, external tool ?)
- [ ] Revise aiidalab-launch to manage multiple containers based on approach identified in previous step

## Dependencies

- [ ] https://github.com/aiidalab/aiidalab-docker-stack/pull/254

**Comment by csadorf** [comment]
I fairly certain this already exists, so probably just requires some adjustment.

**Comment by csadorf** [comment]
@yakutovicha I've made a proposal on how to break up this task into multiple sub-steps in the description above. Please feel free to propose revisions to those. Thank you!

**Comment by yakutovicha** [comment]
I think I have the first somehow working version. 

Here is a bunch of PRs that I am preparing in order to switch to the docker compose approach:

- Update to the docker container https://github.com/aiidalab/aiidalab-docker-stack/pull/254
- Update to the aiidalab-home app https://github.com/aiidalab/aiidalab-home/pull/90
- Switch to docker-compose approach in aiidalab-launch https://github.com/aiidalab/aiidalab-launch/pull/127

More information will follow.

**Comment by csadorf** [comment]
@yakutovicha Could you please briefly document the remaining tasks for this?

**Comment by yakutovicha** [comment]
So, here is the report of what has been done and what needs to be done:

[DONE]
To my knowledge, all the features that are available in the current stable version of the container are implemented in the aforementioned PRs. So from the user perspective, it is almost the same as before with one exception - AiiDA is now installed in a separate conda environment named aiida.

[TODO]
- [ ] Implement handling of the new docker-compose approach within the aiidalab-launch package.
- [ ] Decide whether to keep the old approach of single-docker-image and the new docker compose approach to coexist at least for the transition period.
- [ ] Identify the API changes and ensure a smooth transition from a single-docker-image to the docker-compose.
- [ ] Update the tests, making sure they pass.

**Comment by csadorf** [comment]
@yakutovicha Can you please create an issue for each individual unit of work and link them here as well as in the roadmap?

**Comment by unkcpz** [comment]
I add the stack image https://github.com/aiidalab/aiidalab-docker-stack/pull/319 and tested that it can be started with the services.

**Comment by edan-bainglass** [comment]
TBD, since aiida-core 2.9 now brings in ZMQ
